@startuml
interface ITestMark {
    StudentUsrName : string <<get>> <<set>>
    getStudentMark(maxScore:int) : int
}
class "List`1"<T> {
}
ITestMark --> "Marks<int>" "List`1"
ITestMark --> "TimeSpent" TimeSpan
@enduml
