@startuml
interface IUser {
    Password : string <<get>> <<set>>
    SecretAnswer : string <<get>> <<set>>
    SecretQuestion : string <<get>> <<set>>
    Username : string <<get>> <<set>>
}
@enduml
